config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :carts
  resources :carts
  resources :products
  devise_for :users

  root "home#index"
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    @cart_item = CartItem.new(cart_item_params)

    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully created.' }
        format.json { render :show, status: :created, location: @cart_item }
      else
        format.html { render :new }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:cart_id, :product_id, :quantity, :total)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id, :items_count, :total)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@products = Product.all 
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :name, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart_items/_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h4>

      <ul>
      <% @cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :total %><br>
    <%= f.text_field :total, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit, class: 'btn btn-info' %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cart Items</h1>

<table>
  <thead>
    <tr>
      <th>Cart</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.cart %></td>
        <td><%= cart_item.product %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= cart_item.total %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cart:</strong>
  <%= @cart_item.cart %>
</p>

<p>
  <strong>Product:</strong>
  <%= @cart_item.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart_item.quantity %>
</p>

<p>
  <strong>Total:</strong>
  <%= @cart_item.total %>
</p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :items_count %><br>
    <%= f.number_field :items_count, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :total %><br>
    <%= f.text_field :total, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Save Cart", class: 'btn btn-info' %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Items count</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user %></td>
        <td><%= cart.items_count %></td>
        <td><%= cart.total %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user %>
</p>

<p>
  <strong>Items count:</strong>
  <%= @cart.items_count %>
</p>

<p>
  <strong>Total:</strong>
  <%= @cart.total %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/home/index.html.erb
<% unless @products.blank? %>
  <div class="row">
    <div class="col-lg-12">
      <h3>Products</h3>
      <hr>
    </div>
  </div>

  <div class="row text-center">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
          <%= image_tag('img.jpg') %>
          <div class="caption">
            <h3><%= product.name %></h3>
            <p><%= number_to_currency(product.price)  %></p>
            <p>
              <% if user_signed_in? %>
                <a href="#" class="btn btn-primary">Add to Cart</a></p>
              <% end %>
              <%= link_to 'Show', product, class: 'btn btn-info' %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<% if @products.blank? %>
  <h3 class="text-center">No Products Available</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estore</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "E-STORE", root_path, class: 'navbar-brand' %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <!-- <ul class="nav navbar-nav">
          <li>
            <a href="#">About</a>
          </li>
          <li>
            <a href="#">Services</a>
          </li>
          <li>
            <a href="#">Contact</a>
          </li>
        </ul> -->
        <% if user_signed_in? %>
          <p class="navbar-text navbar-right">Signed in as <%= current_user.email %>, <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></p>
        <% else %>
          <p class="navbar-text navbar-right"><a href="users/sign_in" class="navbar-link">Sign In</a></p>
        <% end %>  
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>

  <!-- Page Content -->
  <div class="container">
    <% if notice %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% elsif alert %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>
    <!-- Main Content Goes Here 
    ================================== -->
    <%= yield %>
    <!-- ============================= -->
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script>
    $(".alert").fadeTo(2000, 500).slideUp(500, function(){
      $(".alert").alert('close');
    });
  </script>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :code %><br>
    <%= f.text_field :code, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "Save Product", class: 'btn btn-info' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @product, class: 'btn btn-warning' %>

app/views/products/index.html.erb
<h2>Listing Products</h2>
<hr>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><strong><%= product.code %></strong></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= truncate(product.description, length: 75) %></td>
        <td><%= link_to 'Show', product, class: 'btn btn-info btn-sm' %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: 'btn btn-default' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h2 class="page-title"><%= @product.name %></h2>
<table class="table table-striped table-hover">
	<tr>
	  <th>Code:</th>
	  <td><%= @product.code %></td>
	</tr>

	<tr>
	  <th>Name:</th>
	  <td><%= @product.name %></td>
	</tr>

	<tr>
	  <th>Price:</th>
	  <td><%= @product.price %></td>
	</tr>

	<tr>
	  <th>Description:</th>
	  <td><%= @product.description %></td>
	</tr>
</table>

<%= link_to 'Back', products_path, class: 'btn btn-default' %>
<%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-warning' %>